//! Go module-tree integrity; no extraction or execution.
//! Algorithm: <https://go.dev/src/cmd/vendor/golang.org/x/mod/sumdb/dirhash/hash.go>
use sha2::{Digest, Sha256};

/// Go's x/mod/sumdb/dirhash.HashZip + Hash1: sorted names, each preceded by
/// its content SHA-256 and two spaces. Hashes include the module@version/
/// prefix and directory entries, exactly as HashZip does. Never extracts or
/// executes files. Unsupported/malformed archives and budget exhaustion are
/// unverified, not a digest mismatch. This is integrity, not trust in a module.
pub(super) fn zip_h1(bytes: &[u8]) -> Option<String> {
    use base64::Engine as _;
    use std::io::{Cursor, Read};
    const MAX_BYTES: u64 = 500 * 1024 * 1024;
    let mut zip = zip::ZipArchive::new(Cursor::new(bytes)).ok()?;
    if zip.len() > 100_000 {
        return None;
    }
    let mut names = std::collections::BTreeMap::new();
    let mut total = 0u64;
    let mut name_bytes = 0usize;
    for i in 0..zip.len() {
        let file = zip.by_index(i).ok()?;
        let name = file.name();
        name_bytes = name_bytes.checked_add(name.len())?;
        if name_bytes > 16 * 1024 * 1024 || file.name_raw() != name.as_bytes() {
            return None;
        }
        if name.len() > 4096
            || name.contains(['\n', '\r', '\0', '\\'])
            || file.enclosed_name().is_none()
            || names.insert(name.to_string(), i).is_some()
        {
            return None;
        }
        total = total.checked_add(file.size())?;
        if total > MAX_BYTES {
            return None;
        }
    }
    let mut tree = Sha256::new();
    let mut actual_total = 0u64;
    for (name, i) in names {
        let mut file = zip.by_index(i).ok()?;
        let mut digest = Sha256::new();
        let mut buf = [0u8; 32768];
        loop {
            let count = file.read(&mut buf).ok()?;
            if count == 0 {
                break;
            }
            actual_total = actual_total.checked_add(count as u64)?;
            if actual_total > MAX_BYTES {
                return None;
            }
            digest.update(&buf[..count]);
        }
        tree.update(format!("{}  {}\n", hex::encode(digest.finalize()), name).as_bytes());
    }
    Some(base64::engine::general_purpose::STANDARD.encode(tree.finalize()))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
pub(super) mod tests {
    use super::*;
    use std::io::{Cursor, Write};

    pub(in crate::fetch) fn archive(
        reverse: bool,
        method: zip::CompressionMethod,
        name: &str,
        content: &str,
    ) -> Vec<u8> {
        let mut zip = zip::ZipWriter::new(Cursor::new(Vec::new()));
        let mut files = vec![
            ("example.test/m@v1.0.0/go.mod", "module example.test/m\n"),
            (name, content),
        ];
        if reverse {
            files.reverse();
        }
        for (name, value) in files {
            let Ok(()) = zip.start_file(
                name,
                zip::write::SimpleFileOptions::default().compression_method(method),
            ) else {
                return Vec::new();
            };
            if zip.write_all(value.as_bytes()).is_err() {
                return Vec::new();
            }
        }
        zip.finish()
            .map_or_else(|_| Vec::new(), std::io::Cursor::into_inner)
    }

    #[test]
    fn golden_hash_is_independent_of_zip_encoding() {
        // Independently computed Hash1 summary, not generated by zip_h1.
        let expected = "7gPDTdAetOil7VBHFXxFU4lStBctQ7LKO/0XF15Bdy8=";
        for method in [
            zip::CompressionMethod::Stored,
            zip::CompressionMethod::Deflated,
        ] {
            for reverse in [false, true] {
                let data = archive(reverse, method, "example.test/m@v1.0.0/m.go", "package m\n");
                assert_eq!(zip_h1(&data).as_deref(), Some(expected));
            }
        }
        for (name, content) in [
            ("example.test/m@v1.0.0/m.go", "package changed\n"),
            ("example.test/m@v1.0.0/other.go", "package m\n"),
        ] {
            let data = archive(false, zip::CompressionMethod::Stored, name, content);
            assert_ne!(zip_h1(&data).as_deref(), Some(expected));
        }
    }

    #[test]
    fn malformed_or_ambiguous_archives_are_unverified() {
        assert_eq!(zip_h1(b"not a zip"), None);
        for name in [
            "../escape.go",
            "/absolute.go",
            "line\nbreak.go",
            "back\\slash.go",
        ] {
            let data = archive(false, zip::CompressionMethod::Stored, name, "package m\n");
            assert_eq!(zip_h1(&data), None, "{name}");
        }
        let mut data = archive(
            false,
            zip::CompressionMethod::Stored,
            "example.test/m@v1.0.0/m.go",
            "package m\n",
        );
        let position = data
            .windows(10)
            .position(|part| part == b"package m\n")
            .unwrap();
        data[position] ^= 1;
        assert_eq!(zip_h1(&data), None, "CRC errors must not verify");
    }
}
